import gql from 'graphql-tag';

export const FICHA_CATASTRAL = gql`
query fichaCatastral($suministro: Int!) {
    comercial {
      fichaCatastral(suministro: $suministro) {
        v_num_inscripcion
        tipo_suministro
        tipo_servicio
        categoria_principal
        tipo_documento
        id_cliente
        tipo_responsable
        apellido_paterno
        apellido_materno
        nombre_cliente
        razon_social
        email_cliente
        telefono_cliente
        celular_cliente
        id_provincia
        id_distrito
        id_sector_comercial
        id_manzana
        lote
        sublote
        estado_predio
        id_ciclo
        localidad
        descripcion_sector_agua
        descripcion_sector_desague
        id_ruta_lectura
        num_secuencia_lectura
        num_ruta_reparto
        num_secuencia_reparto
        tipo_via
        descripcion_via
        tipo_zona
        descripcion_zona
        manzana_predio
        lote_predio
        numero_municipal
        nro_departamento
        piso
        referencia
        tipo_propiedad
        situacion_predio
        tipo_construccion
        material_contruccion
        tipo_reservorio
        tipo_abastecimiento
        tipo_alcantarillado
        tipo_huerto_jardin
        num_pisos
        num_habitantes
        flag_habitado
        posee_jardin
        tiene_medidor
        id_medidor
        diametro_medidor
        fecha_instalacion_medidor
        estado_conservacion
        marca_medidor
        flag_precinto_seguridad
        flag_visor_imposibilidad_lectura
        ubicacion_medidor
        llaves_paso
        seguridad_medidor
        posicion_medidor
        flag_posee_trampa_grasa
        flag_punto_muestreo
        fecha_conexion_agua
        situacion_agua
        ubicacion_caja_agua
        diametro_con_agua
        marco_tapa_con_agua
        material_caja_agua_agua
        material_marco_tapa_agua
        material_con_agua
        estado_marco_tapa_agua
        estado_caja_agua
        fecha_conexion_desague
        situacion_desague
        ubicacion_caja_desague
        diametro_con_desague
        marco_tapa_con_desague
        material_caja_desague
        material_marco_tapa_desague
        material_tapa_desague
        estado_tapa_desague
        estado_caja_desague
        frontera_predio
        area_lote
        area_construida
        si_tiene_pista
        no_tiene_pista
        material_pista
        nivel_presion
        si_tiene_vereda
        no_tiene_vereda
        si_conexion_agua_interior
        no_conexion_agua_interior
        si_conexion_desague_interior
        no_conexion_desague_interior
        si_casa_sirve_negocio
        no_casa_sirve_negocio
        si_area_negocio_punto_agua
        no_area_negocio_punto_agua
        tipo_piscina
        ubicacion_limite_agua
        ubicacion_frontera_agua
        ubicacion_limite_desague
        ubicacion_frontera_desague
        unidades_uso {
          v_num_unidad_uso
          v_desc_categoria
          v_num_habitantes_uu
          v_id_ciuu_t
          v_desc_ciuu
          v_nombre_comercial
        }
      }
    }
  }  
`;