# Imagen base oficial de Node 10
FROM node:10

# Crear directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto
EXPOSE 3030

# Comando de inicio
CMD ["npm", "start"]
